Rewritten test routines. Still need updated reference data. Reasonable tolerances should be also determined.

diff --git a/testsuite/xc-run_testsuite b/testsuite/xc-run_testsuite
--- a/testsuite/xc-run_testsuite
+++ b/testsuite/xc-run_testsuite
@@ -10,40 +10,46 @@ if [ -z "$srcdir" ]; then
   srcdir="./"
 fi
 
+if [ -z "$tmpdir" ]; then
+  tmpdir="/tmp"
+fi
+
 if [ -z "$builddir" ]; then
   builddir="./"
 fi
 
-ok=0
+fail=0
 echo -e "\033[33;1mComparing against reference data\033[0m"
-for i in `ls $srcdir/regression/*.data.bz2 | sort`; do
-  bunzip2 -c $i >/tmp/$$.data_ref
-
-  func=`basename $i .data.bz2`
+for i in `ls $srcdir/regression/*.pol.bz2 | sort`; do
+  func=`basename $i .pol.bz2`
   fname=`printf '%-30s' $func`
-  echo -ne "\033[0m :: Testing \033[35;1m$fname"
-  $builddir/xc-regression $func >/tmp/$$data_test
 
-  res=`diff -q /tmp/$$.data_ref /tmp/$$data_test`
-  if [ "x$res" = "x" ]; then
-    echo -e "\033[32;1mOK"
+  echo -ne "\033[0m :: Testing \033[35;1m$fname"
+
+  bunzip2 -c $srcdir/regression/$func.pol.bz2 > $tmpdir/$$.pol_ref
+  bunzip2 -c $srcdir/regression/$func.unpol.bz2 > $tmpdir/$$.unpol_ref
+
+  $builddir/xc-regression $func $srcdir/input/BrOH+ $tmpdir/$$.pol $tmpdir/$$.unpol > /dev/null
+
+  # Spin-restricted
+  res=`$builddir/xc-error $tmpdir/$$.unpol $tmpdir/$$.unpol_ref`
+  if [ "x$res" = "x1" ]; then
+      echo -ne "\033[32;1mOK"
   else
-    echo -e "\033[31;1mFAIL"
-    ok=$((ok + 1));
+      echo -ne "\033[31;1mFAIL"
+      let fail++
+  fi
+
+  # Spin-unrestricted
+  res=`$builddir/xc-error $tmpdir/$$.pol $tmpdir/$$.pol_ref`
+  if [ "x$res" = "x1" ]; then
+      echo -e "\t\033[32;1mOK"
+      let ok++
+  else
+      echo -e "\t\033[31;1mFAIL"
   fi
 done
 echo -e "\033[0m"
 
-exit $ok
+exit $fail
 
-#echo -e "\033[33;1mInternal consistency\033[0m"
-#for i in `grep -E 'XC_LDA|XC_GGA' $srcdir/../src/xc_funcs.h | awk '{printf("%s,%d\n",$2, $3)}'`; do
-#  func=`echo $i|sed 's/,.*//'`;
-#  number=`echo $i|sed 's/.*,//'`;
-#
-#  if [ $number -ne 6 -a $number -ne 160 ]; then
-#    echo -e "\033[0m :: Testing \033[32;1m$func\033[0m ($number)"
-#    ./xc-consistency $number
-#  fi
-#  echo
-#done
